"""your message

Revision ID: 785135e41a43
Revises: 0e12555d4c52
Create Date: 2023-10-01 22:32:42.151958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785135e41a43'
down_revision = '0e12555d4c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
